#define TEMPLATE_2WH_ALONG			1
#define TEMPLATE_2WH_PERP			2
#define TEMPLATE_3WH_120DEG			3
#define TEMPLATE_3WH_2ALONG_1PERP	4
#define TEMPLATE_4WH_2ALONG_2PERP	5
#define TEMPLATE_4WH_ALONG_OMNI		6
#define TEMPLATE_CUSTOM				7

#define STATUS_STOP					0
#define STATUS_RUN_FWD				1
#define STATUS_RUN_BACK				2
#define STATUS_RUN_RIGHT			3
#define STATUS_RUN_LEFT				4
#define STATUS_TURN_CW				5
#define STATUS_TURN_ACW				6