#define TYPE_BIN_BASIC		1
#define TYPE_BIN_OMNY		2
#define TYPE_DYNAMIC_BASIC	3
#define TYPE_DYNAMIC_OMNY	4

#define STATUS_STOP			0
#define STATUS_CW			1
#define STATUS_ACW			2
#define STATUS_DISABLE 		3

#define PLACEMENT_SIDE_ALONG_RIGHT	1
#define PLACEMENT_SIDE_ALONG_LEFT	2
#define PLACEMENT_SIDE_PERP_FRONT	3
#define PLACEMENT_SIDE_PERP_BACK	4